[package]
edition.workspace = true
version.workspace = true

name = "ui-test-suite"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

hilen = { workspace = true, features = ["inspect", "ui-tests"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { workspace = true }

[build-dependencies]
plat = { workspace = true }

[lints]
workspace = true
