[files]
extend-exclude = ["*.pbxproj", "profile.json"]

[default.extend-words]
# LOD - level of detail
lod = "lod"
# FULL HD
hd = "hd"
# trak - OpenType tracking table
trak = "trak"
# UDID - Apple unique device identifier
udid = "udid"
# numer_denom_ms - the image crate gif frame delay accessor
numer = "numer"
