[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "inspector"
version.workspace = true

[[bin]]
name = "inspector"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
mdns-sd = { workspace = true }
parking_lot = { workspace = true }

hilen = { workspace = true, features = ["inspect"] }

[lints]
workspace = true
