[package]
edition.workspace = true
version.workspace = true

name = "ui-test"

[[bin]]
name = "ui-test"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }

hilen = { workspace = true, features = ["inspect", "ui-tests"] }
demo = { workspace = true }
ui-test-suite = { workspace = true }

[lints]
workspace = true
